CC = cc
CFLAGS = -Wall -Werror -fPIC
LDFLAGS = -shared
TARGET = libctemplate.so

SRCS = libctemplate.c
OBJS = ${SRCS:.c=.o}

all: ${TARGET}

${TARGET}: ${OBJS}
	${CC} ${LDFLAGS} -o $@ ${OBJS}

clean:
	rm -f ${OBJS} ${TARGET}

